.gitignore
Dockerfile
build.gradle
docker-compose.yml
initdb/init.sql
src/main/java/com/planu/group_meeting/GroupMeetingApplication.java
src/main/java/com/planu/group_meeting/config/CorsMvcConfig.java
src/main/java/com/planu/group_meeting/config/RedisConfig.java
src/main/java/com/planu/group_meeting/config/SecurityConfig.java
src/main/java/com/planu/group_meeting/config/auth/CustomUserDetails.java
src/main/java/com/planu/group_meeting/config/auth/CustomUserDetailsService.java
src/main/java/com/planu/group_meeting/controller/TestController.java
src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/dto/UserDto.java
src/main/java/com/planu/group_meeting/entity/Role.java
src/main/java/com/planu/group_meeting/entity/User.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/exception/user/DuplicatedEmailException.java
src/main/java/com/planu/group_meeting/exception/user/DuplicatedUsernameException.java
src/main/java/com/planu/group_meeting/exception/user/InvalidTokenException.java
src/main/java/com/planu/group_meeting/jwt/JwtFilter.java
src/main/java/com/planu/group_meeting/jwt/JwtUtil.java
src/main/java/com/planu/group_meeting/jwt/LoginFilter.java
src/main/java/com/planu/group_meeting/service/UserService.java
src/main/java/com/planu/group_meeting/util/CookieUtil.java
src/main/resources/application.properties
src/main/resources/mapper/UserMapper.xml
src/main/resources/mybatis-config.xml

1. **회원가입**
2. **로그인**
- 로그인 성공 시 : Access, Refresh 토큰 발급
3. **토큰 재발급**
- Refresh 토큰으로 Access 토큰 재발급

feat: 로그인, 회원가입 구현 (+docker 설정)

---

src/main/java/com/planu/group_meeting/config/auth/CustomUserDetails.java
src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/jwt/JwtFilter.java
src/main/java/com/planu/group_meeting/jwt/JwtUtil.java
src/main/java/com/planu/group_meeting/jwt/LoginFilter.java
src/main/java/com/planu/group_meeting/service/UserService.java

>#12
> - 클라이언트가 Authorization 헤더에서 Bearer <access_token> 형식으로 토큰을 받을 수 있도록 수정
> -

refactor: jwt 발급 및 인증 로직 리팩토링

---

src/main/java/com/planu/group_meeting/dto/ScheduleDto.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java

> #27
> - 일성 생성 유효성 검사 기능 구현
> -

feat: 일성 생성 유효성 검사 기능 구현

---

build.gradle
src/main/java/com/planu/group_meeting/config/SecurityConfig.java
src/main/java/com/planu/group_meeting/config/SwaggerConfig.java

feat: swagger 설정

---

src/main/java/com/planu/group_meeting/config/SecurityConfig.java
src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/dto/UserDto.java
src/main/java/com/planu/group_meeting/entity/User.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/exception/file/InvalidFileTypeException.java
src/main/java/com/planu/group_meeting/service/UserService.java
src/main/java/com/planu/group_meeting/service/file/S3Uploader.java
src/main/resources/application.properties
src/main/resources/mapper/UserMapper.xml

> ex) #37
> - 프로필 이미지 설정 기능 구현 
> - 생일 필드 타입 수정

feat: 프로필 이미지 설정 api 구현

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dao/GroupDAO.java
src/main/java/com/planu/group_meeting/dto/GroupInviteResponseDTO.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/java/com/planu/group_meeting/valid/InputValidator.java
src/main/resources/mapper/GroupMapper.xml

> ex) #19 
> -  그룹 초대 기능 추가
> -

feat: 그룹(채팅방) 초대 기능 추가

---

src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/dto/UserDto.java
src/main/java/com/planu/group_meeting/entity/User.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java

fix: 성별 유효성 검사 수정

---

src/main/java/com/planu/group_meeting/controller/AvailableDateController.java
src/main/java/com/planu/group_meeting/dao/AvailableDateDAO.java
src/main/java/com/planu/group_meeting/dto/AvailableDateDto.java
src/main/java/com/planu/group_meeting/service/AvailableDateService.java
src/main/resources/mapper/AvailableDateMapper.xml

> ex) #56
> - 가능한 날짜 조회 기능 구현
> -

feat: 가능한 날짜 조회 기능 구현

---

src/main/java/com/planu/group_meeting/config/SecurityConfig.java
src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/dto/UserDto.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/exception/user/NotFoundUserException.java
src/main/java/com/planu/group_meeting/service/UserService.java
src/main/resources/mapper/UserMapper.xml

feat: 아이디 찾기 기능 구현

---

src/main/java/com/planu/group_meeting/config/SecurityConfig.java
src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/dto/UserDto.java
src/main/java/com/planu/group_meeting/entity/User.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/exception/user/EmailMismatchException.java
src/main/java/com/planu/group_meeting/service/UserService.java
src/main/resources/mapper/UserMapper.xml

> ex) #60
> -  비밀번호 변경 기능 구현
> -

feat: 비밀번호 변경 기능 구현

---

src/main/java/com/planu/group_meeting/controller/AvailableDateController.java
src/main/java/com/planu/group_meeting/controller/ScheduleController.java
src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/dto/BaseResponse.java
src/main/java/com/planu/group_meeting/dto/ScheduleDto.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/jwt/JwtFilter.java
src/main/resources/mapper/ScheduleMapper.xml

refactor: 응답 방식 리팩토링

---

src/main/java/com/planu/group_meeting/config/CorsMvcConfig.java
src/main/java/com/planu/group_meeting/config/SecurityConfig.java

fix: cors 설정

---

src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/dto/UserDto.java
src/main/java/com/planu/group_meeting/service/UserService.java

> ex) #70
> - 사용자 정보 조회 기능 구현
> -

feat: 사용자 정보 조회 기능 구현

---

src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/dto/ScheduleDto.java
src/main/java/com/planu/group_meeting/dto/UserDto.java
src/main/java/com/planu/group_meeting/service/UserService.java

> ex) #74
> -  프로필 이미지 등록 버그 수정
> -

fix: 프로필 이미지 등록 버그 수정

---

src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/dto/ScheduleDto.java
src/main/java/com/planu/group_meeting/dto/UserDto.java
src/main/java/com/planu/group_meeting/service/UserService.java

dev to main

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dao/GroupDAO.java
src/main/java/com/planu/group_meeting/dto/GroupResponseDTO.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/GroupMapper.xml

> ex) #77 
> - 그룹 목록 조회 기능 추가
> -

feat: 그룹 목록 조회 기능 추가

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/service/GroupService.java

> ex) #80 
> - 그룹 초대 목록 조회 기능 추가
> -

feat: 초대 목록 조회 기능 추가

---

src/main/java/com/planu/group_meeting/service/UserService.java
src/main/java/com/planu/group_meeting/service/file/S3Uploader.java
src/main/resources/mapper/UserMapper.xml

> ex) #84
> - 기본 프로필 이미지 등록
> -

feat: 기본 프로필 이미지 등록

---

src/main/java/com/planu/group_meeting/controller/ScheduleController.java
src/main/java/com/planu/group_meeting/dao/ParticipantDAO.java
src/main/java/com/planu/group_meeting/dao/ScheduleDAO.java
src/main/java/com/planu/group_meeting/dao/UnregisteredParticipantDAO.java
src/main/java/com/planu/group_meeting/entity/Schedule.java
src/main/java/com/planu/group_meeting/service/ScheduleService.java
src/main/java/com/planu/group_meeting/service/UserService.java
src/main/resources/mapper/ParticipantMapper.xml
src/main/resources/mapper/ScheduleMapper.xml
src/main/resources/mapper/UnregisteredParticipantMapper.xml

> ex) #89
> -  개인일정 수정 기능 구현
> -

feat: 개인일정 수정 기능 구현

---

src/main/java/com/planu/group_meeting/controller/ScheduleController.java
src/main/java/com/planu/group_meeting/dao/ScheduleDAO.java
src/main/java/com/planu/group_meeting/dto/ScheduleDto.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/exception/user/UnauthorizedResourceException.java
src/main/java/com/planu/group_meeting/service/ScheduleService.java
src/main/resources/mapper/ScheduleMapper.xml

> ex) #91
> -  개인일정 삭제 기능 구현
> -

feat: 개인일정 삭제 기능 구현

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dao/GroupDAO.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/GroupMapper.xml

> ex) #94 
> - 그룹 탈퇴 기능 추가 및 그룹 관련 예외 메시지 수정
> -

feat: 그룹 탈퇴 기능 추가 및 예외 메시지 수정

---

src/main/java/com/planu/group_meeting/controller/FriendController.java
src/main/java/com/planu/group_meeting/dao/FriendDAO.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/exception/user/FriendRequestNotFoundException.java
src/main/java/com/planu/group_meeting/service/UserService.java
src/main/resources/mapper/FriendMapper.xml

> ex) #103
> -  친구요청 수락 기능 
> -

feat: 친구 요청 수락 기능

---

src/main/java/com/planu/group_meeting/controller/FriendController.java
src/main/java/com/planu/group_meeting/dao/FriendDAO.java
src/main/java/com/planu/group_meeting/dto/FriendDto.java
src/main/java/com/planu/group_meeting/service/FriendService.java
src/main/java/com/planu/group_meeting/service/UserService.java
src/main/resources/mapper/FriendMapper.xml

> ex) #107
> - 친구 목록 조회 기능
> -

feat: 친구 목록 조회 기능

---

src/main/java/com/planu/group_meeting/controller/FriendController.java
src/main/java/com/planu/group_meeting/dao/FriendDAO.java
src/main/java/com/planu/group_meeting/service/FriendService.java
src/main/resources/mapper/FriendMapper.xml

> ex) #109
> -  친구 요청 거절 기능 구현
> -

feat: 친구 요청 거절 기능

---

src/main/java/com/planu/group_meeting/controller/FriendController.java
src/main/java/com/planu/group_meeting/service/FriendService.java

> ex) #111
> - 친구 요청 취소 기능 구현
> -

feat: 친구 요청 취소 기능

---

src/main/java/com/planu/group_meeting/controller/FriendController.java
src/main/java/com/planu/group_meeting/dao/FriendDAO.java
src/main/java/com/planu/group_meeting/service/FriendService.java
src/main/resources/mapper/FriendMapper.xml

> ex) #이슈번호
> - 친구 요청 보낸 목록 조회
> -

feat: 친구 요청 보낸 목록 조회

---

src/main/java/com/planu/group_meeting/controller/FriendController.java
src/main/java/com/planu/group_meeting/service/FriendService.java

> ex) #115
> - 친구 요청 받은 목록 조회
> -

feat: 친구 요청 받은 목록 조회

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dao/GroupDAO.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/GroupMapper.xml

> ex) #118 
> - 그룹 삭제기능 추가
> -

feat: 그룹 삭제 기능 추가

---

src/main/java/com/planu/group_meeting/dao/GroupDAO.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/GroupMapper.xml

> ex) #120 
> - 초대목록 조회 기능 수정
> -

fix: 초대목록 조회기능 수정

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/service/GroupService.java

> ex) #122 
> - 초대 거절 기능 추가
> -

feat: 초대 거절 기능 추가

---

src/main/java/com/planu/group_meeting/controller/GroupScheduleController.java
src/main/java/com/planu/group_meeting/dao/GroupScheduleDAO.java
src/main/java/com/planu/group_meeting/dao/GroupScheduleParticipantDAO.java
src/main/java/com/planu/group_meeting/dao/GroupScheduleUnregisteredParticipantDAO.java
src/main/java/com/planu/group_meeting/dto/GroupScheduleDTO.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java
src/main/resources/mapper/GroupScheduleMapper.xml
src/main/resources/mapper/GroupScheduleParticipantMapper.xml
src/main/resources/mapper/GroupScheduleUnregisteredParticipantMapper.xml

> ex) #100 
> -그룹 일정 상세 조회 API를 만들었습니다. 이후, 그룹 일정에 달린 코멘트 리스트 조회 API까지 만들면 최종 완성입니다.
> -

feat: 그룹 일정 상세 조회 API

---

src/main/java/com/planu/group_meeting/controller/FriendController.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/service/FriendService.java

feat: 친구 삭제 기능

---

src/main/java/com/planu/group_meeting/controller/GroupScheduleController.java
src/main/java/com/planu/group_meeting/dao/GroupScheduleDAO.java
src/main/java/com/planu/group_meeting/dao/GroupScheduleParticipantDAO.java
src/main/java/com/planu/group_meeting/dao/GroupScheduleUnregisteredParticipantDAO.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/GroupScheduleMapper.xml
src/main/resources/mapper/GroupScheduleParticipantMapper.xml
src/main/resources/mapper/GroupScheduleUnregisteredParticipantMapper.xml

> ex) #129 
> 그룹 일정을 삭제하는 API를 추가하였습니다
> -

feat: 그룹 일정 삭제 API 구현

---

src/main/java/com/planu/group_meeting/controller/GroupScheduleController.java
src/main/java/com/planu/group_meeting/dao/GroupScheduleDAO.java
src/main/java/com/planu/group_meeting/dto/ScheduleDto.java
src/main/java/com/planu/group_meeting/entity/GroupSchedule.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java
src/main/resources/mapper/GroupScheduleMapper.xml

> ex) #131 
> -  그룹 일정의 세부 내용을 수정하는 API입니다.
> -

feat: 그룹 일정 수정 API 구현

---

src/main/java/com/planu/group_meeting/config/SwaggerConfig.java
src/main/java/com/planu/group_meeting/controller/AvailableDateController.java
src/main/java/com/planu/group_meeting/controller/FriendController.java
src/main/java/com/planu/group_meeting/controller/ScheduleController.java
src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/controller/docs/AvailableDateDocs.java
src/main/java/com/planu/group_meeting/controller/docs/FriendDocs.java
src/main/java/com/planu/group_meeting/controller/docs/ScheduleDocs.java
src/main/java/com/planu/group_meeting/controller/docs/UserDocs.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/jwt/LoginFilter.java
src/main/resources/application.properties

feat: 스웨거 설정

---

src/main/java/com/planu/group_meeting/config/SwaggerConfig.java
src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/controller/docs/UserDocs.java

feat: 스웨거 cors 설정

---

src/main/java/com/planu/group_meeting/dto/ScheduleDto.java
src/main/java/com/planu/group_meeting/entity/common/FriendStatus.java
src/main/java/com/planu/group_meeting/service/ScheduleService.java
src/main/resources/mapper/UserMapper.xml

> ex) #147
> - 일정 유무 응답 형식 boolean 값타입으로 수정
> -

feat: 일정 유무 응답 형식 수정

---

src/main/java/com/planu/group_meeting/controller/ScheduleController.java
src/main/java/com/planu/group_meeting/controller/docs/AvailableDateDocs.java
src/main/java/com/planu/group_meeting/controller/docs/ScheduleDocs.java
src/main/java/com/planu/group_meeting/dao/FriendDAO.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/service/ScheduleService.java

> ex) #151
> -  개인일정 유무 조회 api 수정 (PathVariable 추가)
> -

fix: 개인일정 유무 조회 api 수정 (PathVariable 추가)

---

src/main/java/com/planu/group_meeting/controller/GroupScheduleController.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/exception/group/GroupNotFoundException.java
src/main/java/com/planu/group_meeting/exception/group/UnauthorizedAccessException.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/java/com/planu/group_meeting/service/GroupUserService.java
src/main/resources/mapper/GroupUserMapper.xml

그룹을 찾을 수 없는 경우와 그룹원이 아닌 경우에 대한
오류 처리를 추가하였음.
> ex) #146 
> 그룹이 존재하는지 않는 경우, 그룹원이 아닌 경우에 대한 오류 처리 추가

feat: 그룹 일정 API 오류 처리 추가

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dao/GroupUserDAO.java
src/main/java/com/planu/group_meeting/dto/GroupDTO.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/java/com/planu/group_meeting/service/GroupUserService.java
src/main/resources/mapper/GroupUserMapper.xml

> ex) #134 
> -  그룹원이 아닌 친구 목록을 제공합니다.
> -

feat: 그룹 멤버 초대리스트 API

---

src/main/java/com/planu/group_meeting/controller/GroupController.java

> ex) #164 
> - 초대 수락 api 수정(request param -> path variable)
> -

fix: 초대 수락 api 수정

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dao/GroupUserDAO.java
src/main/java/com/planu/group_meeting/dto/AvailableDateDto.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/GroupUserMapper.xml

> ex) #163 
> 가능한 날짜 정보를 제공합니다.
> -

feat: 가능한 날짜 비율 정보 제공

---

src/main/java/com/planu/group_meeting/config/SecurityConfig.java
src/main/java/com/planu/group_meeting/config/auth/CustomOAuth2UserService.java
src/main/java/com/planu/group_meeting/config/loginhandler/CustomOAuth2LoginSuccessHandler.java
src/main/java/com/planu/group_meeting/config/loginhandler/LoginFilter.java
src/main/java/com/planu/group_meeting/controller/OAuth2Controller.java
src/main/java/com/planu/group_meeting/service/OAuth2Service.java
src/main/java/com/planu/group_meeting/util/CookieUtil.java
src/main/resources/application.properties

fix: 카카오 로그인 수정

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dto/ApiResponse.java

> ex) #172 
> - 그룹 목록 조회, 초대 목록 조회 반환형태 수정
> -

fix: 그룹 목록 조회, 초대 목록 조회 반환형태 수정

---

src/main/java/com/planu/group_meeting/controller/GroupController.java

fix: 초대수락 응답형태 수정

---

src/main/java/com/planu/group_meeting/config/SecurityConfig.java
src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dao/AvailableDateDAO.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/AvailableDateMapper.xml
src/main/resources/mapper/UserMapper.xml

> ex) #170 
> 요청한 날짜의 가능한 그룹 멤버 이름 목록을 가져옵니다.

feat: 해당 날짜 가능한 그룹 멤버 목록

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/dto/GroupDTO.java
src/main/java/com/planu/group_meeting/service/AvailableDateService.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/UserMapper.xml

> ex) #183
> 가능한 날짜 그룹 멤버별 조회 기능 추가

feat: 그룹 가능한 날짜 멤버별 조회

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/service/GroupService.java

> ex) #189 
> 가능한 날짜를 많이 등록한 순서대로 데이터를 제공합니다. (등록한 수는 내림차순, 수가 같다면 날짜는 오름차순으로 제공)

feat: 가능한 날짜 순위 제공

---

src/main/java/com/planu/group_meeting/service/GroupService.java

> ex) #191 
> 상태를 나타내는 문자열을 RECEIVE에서 PROGRESS로 수정

feat: 그룹 상대 초대 리스트 수정

---

src/main/java/com/planu/group_meeting/service/FriendService.java

> ex) #193 
> RECEIVE, REQUEST 반대로 나오는거 수정

fix: 그룹 멤버 목록 수정

---

src/main/java/com/planu/group_meeting/config/SecurityConfig.java
src/main/java/com/planu/group_meeting/controller/NotificationController.java
src/main/java/com/planu/group_meeting/dao/NotificationDAO.java
src/main/java/com/planu/group_meeting/dto/BaseResponse.java
src/main/java/com/planu/group_meeting/dto/NotificationDTO.java
src/main/java/com/planu/group_meeting/exception/CustomAuthenticationEntryPoint.java
src/main/java/com/planu/group_meeting/exception/ExceptionHandlerFilter.java
src/main/java/com/planu/group_meeting/service/NotificationService.java
src/main/java/com/planu/group_meeting/util/CookieUtil.java

> ex) #186
> -  SSE 연결만 해둔 상태
> -

feat: SSE 연결 요청 api

---

src/main/java/com/planu/group_meeting/controller/FriendController.java
src/main/java/com/planu/group_meeting/controller/docs/FriendDocs.java
src/main/java/com/planu/group_meeting/dao/FriendDAO.java
src/main/java/com/planu/group_meeting/service/FriendService.java
src/main/resources/mapper/FriendMapper.xml

> ex) #203
> - 친구목록 검색 기능 구현
> -

feat: 친구 목록 검색 기능 구현

---

src/main/java/com/planu/group_meeting/controller/ScheduleController.java
src/main/java/com/planu/group_meeting/controller/docs/ScheduleDocs.java
src/main/java/com/planu/group_meeting/service/ScheduleService.java

> ex) #205
> -  일정 조회 경로변수 username으로 변경
> -

refactor: 일정 조회 경로변수 username으로 변경

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dto/GroupInviteResponseDTO.java
src/main/java/com/planu/group_meeting/dto/GroupResponseDTO.java

> ex) #208 
> - userName -> username 으로 수정
> -

fix: userName -> username 으로 수정

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dao/GroupDAO.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/GroupMapper.xml

> ex) #212 
> -  그룹 상단고정 해제 기능 추가
> -

feat: 그룹 상단고정 해제 기능 추가

---

src/main/java/com/planu/group_meeting/dto/GroupResponseDTO.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/GroupMapper.xml

> ex) #214 
> - 그룹 목록 조회 기능 추가(상단 고정 기능)
> -

feat: 그룹 목록 조회 기능 추가(상단 고정 기능)

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dao/GroupDAO.java
src/main/java/com/planu/group_meeting/dao/GroupUserDAO.java
src/main/java/com/planu/group_meeting/dto/GroupDTO.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/GroupMapper.xml
src/main/resources/mapper/GroupUserMapper.xml

> ex) #223 
> 그룹 멤버 조회에서 필터링을 통해 검색하는 내용을 추가, 그룹 상세 조회를 추가하였음

feat: 그룹 상세 조회 추가 및 그룹 멤버 조회 수정

---

src/main/java/com/planu/group_meeting/dao/GroupUserDAO.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/GroupUserMapper.xml

검색 기능 수정 및 status 에러 수정
> ex) #230 
status 오류랑 keyword 안되는거 수정하였음.

fix: 그룹 상대 초대 리스트 수정

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/service/GroupService.java

> ex) #232 
> - 그룹 초대 취소 기능 추가
> -

feat: 그룹 초대 취소 기능 추가

---

src/main/java/com/planu/group_meeting/dao/NotificationDAO.java
src/main/java/com/planu/group_meeting/service/NotificationService.java
src/main/resources/mapper/NotificationMapper.xml

feat: 알림 유효기간 설정

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dto/GroupDTO.java
src/main/java/com/planu/group_meeting/service/GroupService.java

> ex) #241 
> 데이터 패킹 및 그룹 이미지 데이터 제외

fix: 그룹 상세 페이지 API 수정

---

src/main/java/com/planu/group_meeting/controller/FriendController.java
src/main/java/com/planu/group_meeting/controller/docs/FriendDocs.java
src/main/java/com/planu/group_meeting/service/FriendService.java

fix: 친구조회 수정

---

src/main/java/com/planu/group_meeting/dao/FriendDAO.java
src/main/java/com/planu/group_meeting/dto/FriendDto.java
src/main/java/com/planu/group_meeting/service/FriendService.java
src/main/resources/mapper/FriendMapper.xml

fix: 친구 요청 예외 로직 수정

---

src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/dto/ScheduleDto.java
src/main/java/com/planu/group_meeting/service/ScheduleService.java
src/main/resources/mapper/UserMapper.xml

> ex) #258
> -  개인달력조회에 그룹원 생일자 조회 추가
> -

feat: 일정 목록 조회에 그룹원 생일도 추가

---

src/main/java/com/planu/group_meeting/controller/NotificationController.java
src/main/java/com/planu/group_meeting/dao/NotificationDAO.java
src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/service/NotificationService.java
src/main/resources/mapper/NotificationMapper.xml

> ex) #260
> -  알림 읽음 처리 기능 구현
> -

feat: 알림 읽음 처리 기능 구현

---

src/main/java/com/planu/group_meeting/config/auth/CustomUserDetails.java
src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dao/GroupUserDAO.java
src/main/java/com/planu/group_meeting/dto/NotificationDTO.java
src/main/java/com/planu/group_meeting/entity/common/EventType.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/java/com/planu/group_meeting/service/NotificationService.java
src/main/resources/mapper/GroupUserMapper.xml
src/main/resources/mapper/UserMapper.xml

> ex) #264
> -  그룹 초대 및 수락 알림 기능 구현
> -

feat: 그룹 초대 및 수락 알림 기능 구현

---

src/main/java/com/planu/group_meeting/dto/GroupScheduleDTO.java
src/main/java/com/planu/group_meeting/dto/NotificationDTO.java
src/main/java/com/planu/group_meeting/entity/common/EventType.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/java/com/planu/group_meeting/service/NotificationService.java
src/main/java/com/planu/group_meeting/service/ScheduleNotificationService.java
src/main/resources/mapper/GroupScheduleParticipantMapper.xml

> ex) #266
> -  그룹 강퇴 알림, 그룹 일정 생성 알림 구현 및 리팩토링
> -

feat: 그룹 일정 생성, 그룹원 추방 알림 구현 및 리팩토링

---

src/main/java/com/planu/group_meeting/controller/GroupScheduleController.java
src/main/java/com/planu/group_meeting/controller/docs/GroupScheduleDocs.java
src/main/java/com/planu/group_meeting/dao/GroupScheduleDAO.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/dto/GroupScheduleDTO.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java
src/main/resources/mapper/GroupScheduleMapper.xml
src/main/resources/mapper/UserMapper.xml

> ex) #267 
> - 그룹 일정 유무 조회 API 및 그룹 일정 API 스웨거에 추가

feat: 그룹 일정 유무 조회 API

---

src/main/java/com/planu/group_meeting/dto/GroupScheduleDTO.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java
src/main/resources/mapper/NotificationMapper.xml
src/main/resources/mapper/ScheduleMapper.xml

> ex) #272
> -  개인 일정 조회 응답 데이터 연,월,시간 형식 수정
> -

refactor: 개인 일정 조회 시간 형식 수정

---

src/main/java/com/planu/group_meeting/controller/GroupScheduleController.java
src/main/java/com/planu/group_meeting/dao/GroupScheduleDAO.java
src/main/java/com/planu/group_meeting/dto/GroupScheduleDTO.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java
src/main/java/com/planu/group_meeting/service/GroupUserService.java
src/main/resources/mapper/GroupScheduleMapper.xml

> ex) #274 
> -  그룹 달력 일정 조회 API 수정

fix: 그룹 달력 일정 조회 API

---

src/main/java/com/planu/group_meeting/controller/GroupScheduleCommentController.java
src/main/java/com/planu/group_meeting/controller/GroupScheduleController.java
src/main/java/com/planu/group_meeting/dao/GroupScheduleCommentDAO.java
src/main/java/com/planu/group_meeting/dto/GroupScheduleCommentDTO.java
src/main/java/com/planu/group_meeting/entity/GroupScheduleComment.java
src/main/java/com/planu/group_meeting/service/GroupScheduleCommentService.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java
src/main/resources/mapper/GroupScheduleCommentMapper.xml
src/main/resources/mapper/GroupScheduleMapper.xml

> ex) #280 
> - 그룹 일정 댓글을 생성합니다.

feat: 그룹 일정 댓글 생성

---

src/main/java/com/planu/group_meeting/exception/GlobalExceptionHandler.java
src/main/java/com/planu/group_meeting/exception/user/InvalidTokenException.java
src/main/java/com/planu/group_meeting/jwt/JwtFilter.java
src/main/java/com/planu/group_meeting/jwt/JwtUtil.java

refactor: 토큰 검증 리팩토링

---

src/main/java/com/planu/group_meeting/entity/GroupScheduleComment.java
src/main/java/com/planu/group_meeting/service/GroupScheduleCommentService.java
src/main/resources/mapper/GroupScheduleCommentMapper.xml

> ex) #289 
> - 그룹 일정 댓글 조회 API 수정

fix: 그룹 일정 댓글 조회 수정

---

src/main/java/com/planu/group_meeting/chat/dao/ChatDAO.java
src/main/java/com/planu/group_meeting/chat/service/ChatService.java
src/main/java/com/planu/group_meeting/dao/ScheduleDAO.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/dto/ScheduleDto.java
src/main/java/com/planu/group_meeting/service/ScheduleService.java
src/main/resources/mapper/ScheduleMapper.xml
src/main/resources/mapper/UserMapper.xml

> ex) #296
> - 개인 일정 목록 조회 시간 값 수정
> -

fix: 개인 일정 목록 조회 수정

---

src/main/java/com/planu/group_meeting/dto/GroupScheduleDTO.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java

시간 포맷팅 수정
> ex) #300
> - 프론트 요청으로 시간 데이터 포맷팅 수정

fix: 그룹 달력 일정 조회 수정

---

src/main/java/com/planu/group_meeting/dao/GroupScheduleDAO.java
src/main/java/com/planu/group_meeting/dto/NotificationDTO.java
src/main/java/com/planu/group_meeting/service/GroupScheduleCommentService.java
src/main/java/com/planu/group_meeting/service/NotificationService.java

> ex) #299
> -  실시간 댓글 알림 기능 구현
> -

feat: 실시간 댓글 알림 기능 구현

---

src/main/java/com/planu/group_meeting/chat/dao/ChatDAO.java
src/main/java/com/planu/group_meeting/chat/dto/MessageStatus.java
src/main/java/com/planu/group_meeting/chat/service/ChatService.java
src/main/java/com/planu/group_meeting/dao/GroupDAO.java
src/main/java/com/planu/group_meeting/dto/GroupUserDTO.java
src/main/resources/mapper/GroupMapper.xml
src/main/resources/mapper/chat/ChatMapper.xml

feat: 채팅 저장로직 완료

---

src/main/resources/mapper/ScheduleMapper.xml

> ex) #308
> - 일정 유무 조회 기능 수정 
> -

fix: 개인 일정 유무 조회 기능 수정

---

src/main/java/com/planu/group_meeting/chat/controller/ChatController.java
src/main/java/com/planu/group_meeting/chat/dao/ChatDAO.java
src/main/java/com/planu/group_meeting/chat/dto/ChatInfo.java
src/main/java/com/planu/group_meeting/chat/dto/response/ChatRoomResponse.java
src/main/java/com/planu/group_meeting/chat/service/ChatService.java
src/main/resources/mapper/chat/ChatMapper.xml

> ex) #307 
> - 채팅방 목록 조회 완료
> -

feat: 채팅방 목록 조회 완료

---

src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/dto/UserDto.java
src/main/java/com/planu/group_meeting/entity/common/CertificationPurpose.java
src/main/java/com/planu/group_meeting/service/UserService.java
src/main/resources/mapper/UserMapper.xml

> ex) #311
> -  이메일 변경 기능 구현
> -

feat: 이메일 변경 기능 구현

---

src/main/resources/mapper/GroupScheduleMapper.xml

fix: 그룹 일정 유무 조회 API 수정

---

src/main/java/com/planu/group_meeting/service/GroupService.java

> - 가능한 날짜를 아무도 등록하지 않았을 시 발생하는 에러 수정

fix: 그룹 가능한 날짜 순위 API 수정

---

src/main/java/com/planu/group_meeting/chat/controller/ChatController.java
src/main/java/com/planu/group_meeting/chat/service/ChatService.java
src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/controller/docs/GroupDocs.java
src/main/java/com/planu/group_meeting/dto/DataResponse.java

faet: 채팅방 검색 기능 추가

---

src/main/java/com/planu/group_meeting/chat/controller/ChatController.java
src/main/java/com/planu/group_meeting/chat/service/ChatService.java
src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/controller/docs/GroupDocs.java
src/main/java/com/planu/group_meeting/dto/DataResponse.java
src/main/java/com/planu/group_meeting/service/UserService.java

채팅방 검색 기능 추가

---

src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/dto/GroupDTO.java

feat: 그룹원 수 조회

---

src/main/java/com/planu/group_meeting/dto/AvailableDateDto.java
src/main/java/com/planu/group_meeting/service/GroupService.java

> ex) #이슈번호
> 가능한 날짜에 투표한 인원 수를 추가하였음.

fix: 가능한 날짜 순위 수정

---

src/main/java/com/planu/group_meeting/controller/FriendController.java
src/main/java/com/planu/group_meeting/dao/FriendDAO.java
src/main/java/com/planu/group_meeting/service/FriendService.java
src/main/resources/mapper/FriendMapper.xml

> ex) #341
> - 추천친구 목록 조회 기능
> -

feat: 추천친구 목록 조회

---

src/main/java/com/planu/group_meeting/chat/dao/ChatDAO.java
src/main/java/com/planu/group_meeting/chat/service/ChatService.java
src/main/java/com/planu/group_meeting/dao/GroupDAO.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/GroupMapper.xml

fix : 채팅관련 오류 수정

---

src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/controller/docs/UserDocs.java
src/main/java/com/planu/group_meeting/dto/UserDto.java
src/main/java/com/planu/group_meeting/service/UserService.java
src/main/java/com/planu/group_meeting/valid/NullablePattern.java
src/main/java/com/planu/group_meeting/valid/NullablePatternValidator.java

fix: 프로필 변경 수정

---

src/main/java/com/planu/group_meeting/chat/dao/ChatDAO.java
src/main/java/com/planu/group_meeting/chat/service/ChatService.java
src/main/resources/mapper/chat/ChatMapper.xml

faet: 새로운 메시지 수 확인 기능

---

src/main/java/com/planu/group_meeting/chat/controller/ChatController.java
src/main/java/com/planu/group_meeting/chat/dto/response/ChatMessageResponse.java

fix : chatResponse에 profileImage 추가

---

src/main/java/com/planu/group_meeting/controller/NotificationController.java
src/main/java/com/planu/group_meeting/dao/NotificationDAO.java
src/main/java/com/planu/group_meeting/dto/NotificationDTO.java
src/main/java/com/planu/group_meeting/service/NotificationService.java
src/main/resources/mapper/NotificationMapper.xml

feat: 읽지 않은 알림 여부 확인 기능

---

src/main/java/com/planu/group_meeting/dao/FriendDAO.java
src/main/java/com/planu/group_meeting/dao/UserDAO.java
src/main/java/com/planu/group_meeting/dto/FriendDto.java
src/main/java/com/planu/group_meeting/dto/NotificationDTO.java
src/main/java/com/planu/group_meeting/dto/UserDto.java
src/main/java/com/planu/group_meeting/entity/common/EventType.java
src/main/java/com/planu/group_meeting/scheduler/NotificationScheduler.java
src/main/java/com/planu/group_meeting/service/NotificationService.java
src/main/java/com/planu/group_meeting/service/ScheduleService.java
src/main/resources/mapper/FriendMapper.xml
src/main/resources/mapper/UserMapper.xml

feat: 생일 알림 기능 구현

---

src/main/java/com/planu/group_meeting/scheduler/NotificationScheduler.java
src/main/java/com/planu/group_meeting/service/NotificationService.java
src/main/java/com/planu/group_meeting/service/ScheduleService.java

feat: 개인달력 유효성 로직 추가

---

src/main/java/com/planu/group_meeting/dto/ScheduleDto.java
src/main/java/com/planu/group_meeting/service/NotificationService.java
src/main/resources/mapper/NotificationMapper.xml

fix: 알림 조회 한국 표준 시간 설정

---

src/main/java/com/planu/group_meeting/service/GroupService.java

fix : 그룹삭제 왜래키 무결성 수정

---

src/main/java/com/planu/group_meeting/controller/NotificationController.java
src/main/java/com/planu/group_meeting/dao/NotificationDAO.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/java/com/planu/group_meeting/service/NotificationService.java
src/main/resources/mapper/NotificationMapper.xml

> ex) #372
> -  알림 전체 읽기 기능과 그룹장에게는 그룹삭제 알림이 가지 않도록 설정
> -

feat: 알림 전체 읽기 api

---

src/main/java/com/planu/group_meeting/controller/GroupScheduleCommentController.java
src/main/java/com/planu/group_meeting/service/GroupScheduleCommentService.java

feat: 그룹 일정 댓글에 isMyComment 추가

---

src/main/java/com/planu/group_meeting/chat/controller/ChatController.java
src/main/java/com/planu/group_meeting/chat/controller/swagger/ChatDocs.java
src/main/java/com/planu/group_meeting/chat/dto/response/ChatMessageResponse.java
src/main/java/com/planu/group_meeting/chat/dto/response/GroupedChatMessages.java
src/main/java/com/planu/group_meeting/chat/service/ChatService.java
src/main/java/com/planu/group_meeting/controller/GroupController.java
src/main/java/com/planu/group_meeting/controller/docs/GroupDocs.java
src/main/java/com/planu/group_meeting/dto/GroupRequestDTO.java
src/main/resources/mapper/chat/ChatMapper.xml

fix: 채팅 기능 수정

---

src/main/java/com/planu/group_meeting/controller/GroupScheduleController.java
src/main/java/com/planu/group_meeting/controller/docs/GroupScheduleDocs.java
src/main/java/com/planu/group_meeting/dto/GroupScheduleDTO.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java

feat: 그룹 일정 장소 위치 조회

---

src/main/java/com/planu/group_meeting/config/loginhandler/CustomOAuth2LoginSuccessHandler.java
src/main/java/com/planu/group_meeting/config/loginhandler/LoginFilter.java

feat: 로그인 성공시 쿠키에 username 담아서 보내기

---

src/main/java/com/planu/group_meeting/controller/ScheduleController.java
src/main/java/com/planu/group_meeting/controller/docs/ScheduleDocs.java
src/main/java/com/planu/group_meeting/dto/ScheduleDto.java
src/main/java/com/planu/group_meeting/service/ScheduleService.java

fix: 응답 수정

---

src/main/resources/mapper/UserMapper.xml

fix: 본인 생일도 일정으로 체크

---

src/main/java/com/planu/group_meeting/exception/CustomAuthenticationEntryPoint.java

fix: 스프링 시큐리티 중복 응답 수정

---

src/main/java/com/planu/group_meeting/controller/docs/GroupScheduleDocs.java
src/main/java/com/planu/group_meeting/dto/GroupScheduleDTO.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java

fix: 그룹 일정 생성 시 제약 수정

---

src/main/java/com/planu/group_meeting/dto/GroupScheduleDTO.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java

fix: 그룹 일정 도착 장소 추가

---

src/main/java/com/planu/group_meeting/chat/controller/ChatController.java
src/main/java/com/planu/group_meeting/chat/controller/swagger/ChatDocs.java
src/main/java/com/planu/group_meeting/chat/dto/request/ChatFileRequest.java
src/main/java/com/planu/group_meeting/chat/service/ChatService.java
src/main/java/com/planu/group_meeting/valid/InputValidator.java

채팅에 사진 업로드 및 전송 기능 추가

---

src/main/java/com/planu/group_meeting/controller/GroupScheduleController.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java
src/main/resources/mapper/GroupScheduleMapper.xml
src/main/resources/mapper/UserMapper.xml

fix: 그룹 일정 조회 버그 수정

---

src/main/java/com/planu/group_meeting/controller/UserController.java
src/main/java/com/planu/group_meeting/util/CookieUtil.java

fix: 로그아웃 username 쿠키 삭제

---

src/main/java/com/planu/group_meeting/chat/handler/StompHandler.java
src/main/java/com/planu/group_meeting/controller/GroupScheduleController.java
src/main/java/com/planu/group_meeting/location/controller/LocationController.java
src/main/java/com/planu/group_meeting/location/service/LocationService.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java

fix: 디버그용 로그 메시지 추가

---

src/main/java/com/planu/group_meeting/chat/controller/ChatController.java
src/main/java/com/planu/group_meeting/chat/controller/swagger/ChatDocs.java
src/main/java/com/planu/group_meeting/chat/dto/response/ChatMessageResponse.java
src/main/java/com/planu/group_meeting/chat/service/ChatService.java

feat: 채팅응답에 사용자이름 추가

---

src/main/java/com/planu/group_meeting/dto/GroupDTO.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java
src/main/java/com/planu/group_meeting/service/GroupService.java

그룹일정 생성시 참석자 검증
> ex) #이슈번호
> - 
> -

feat: 그룹 상세 조회에서 이미지 추가

---

src/main/java/com/planu/group_meeting/chat/service/ChatService.java
src/main/java/com/planu/group_meeting/valid/InputValidator.java

feat: 파일 검증에 동영상 확장자(mp4, mov) 추가

---

src/main/java/com/planu/group_meeting/service/GroupScheduleCommentService.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java

fix: 그룹 일정 생성 시 참여자 리스트 추가

---

src/main/java/com/planu/group_meeting/config/CorsMvcConfig.java
src/main/java/com/planu/group_meeting/config/SecurityConfig.java

feat: 도메인 cors 설정

---

src/main/java/com/planu/group_meeting/service/AvailableDateService.java

fix: 가능한 날짜 선택 제약조건(이전날짜 선택) 삭제

---

src/main/java/com/planu/group_meeting/location/controller/LocationController.java
src/main/java/com/planu/group_meeting/location/controller/docs/LocationControllerDocs.java

feat: 위치 공유 API 스웨거 추가

---

src/main/java/com/planu/group_meeting/config/loginhandler/CustomOAuth2LoginSuccessHandler.java

feat: 카카오 로그인 성공 리다이렉트 경로 수정

---

src/main/java/com/planu/group_meeting/chat/handler/StompHandler.java
src/main/java/com/planu/group_meeting/service/GroupService.java

fix: 가능한 날짜 수정

---

src/main/java/com/planu/group_meeting/dto/GroupScheduleDTO.java
src/main/java/com/planu/group_meeting/service/GroupScheduleService.java

feat: 일정 위치 장소 조회DTO 종료날짜 추가

---

src/main/java/com/planu/group_meeting/chat/handler/StompHandler.java

fix: 종일 일정 검사 로직 수정

---

src/main/java/com/planu/group_meeting/location/service/LocationService.java

fix: 위치 공유 로직 수정

---

src/main/java/com/planu/group_meeting/dto/AvailableDateDto.java
src/main/java/com/planu/group_meeting/service/AvailableDateService.java
src/main/java/com/planu/group_meeting/service/MailService.java
src/main/java/com/planu/group_meeting/service/UserService.java

fix: 이메일 인증 메세지 변경

---

src/main/java/com/planu/group_meeting/dao/GroupScheduleParticipantDAO.java
src/main/java/com/planu/group_meeting/service/GroupService.java
src/main/resources/mapper/GroupScheduleParticipantMapper.xml

feat: 그룹 일정 참석자 로직 추가

---

src/main/java/com/planu/group_meeting/service/GroupService.java

feat: 가능한 날짜 오늘 이후로만 조회하게 수정

---

.github/workflows/deploy.yml
Dockerfile
docker-compose.blue.yml
docker-compose.green.yml
src/main/java/com/planu/group_meeting/exception/CustomAuthenticationEntryPoint.java
src/main/java/com/planu/group_meeting/service/AvailableDateService.java
src/main/java/com/planu/group_meeting/util/CookieUtil.java

feat: blue-green 무중단 배포 설정

---

.github/workflows/deploy.yml
docker-compose.blue.yml
docker-compose.green.yml
docker-compose.shared.yml

feat: docker-compose.yml 수정

---

.gitignore
Dockerfile
docker-compose.nginx.yml
nginx/conf_d/default.conf

feat: nginx https 설정 파일 작성
